# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shale < Formula
  desc "Agent PR evidence — intent capture and session evidence rendered on pull requests"
  homepage "https://github.com/provasign/shale"
  version "0.1.26"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/provasign/shale/releases/download/v0.1.26/shale_darwin_amd64.tar.gz"
      sha256 "ab82bff991cf72602756b463cd20d33fbb782c56b549a2eaaca7558731810d32"

      define_method(:install) do
        bin.install "shale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/provasign/shale/releases/download/v0.1.26/shale_darwin_arm64.tar.gz"
      sha256 "ad58af58d1db3034729beb73be2a2f47a1b23fa706fdbb765f81a559d55c6b5c"

      define_method(:install) do
        bin.install "shale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/provasign/shale/releases/download/v0.1.26/shale_linux_amd64.tar.gz"
      sha256 "4dac84166e6bae0cde1531fb35e8b96988448734884995e12b99ecbc610f33e0"
      define_method(:install) do
        bin.install "shale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/provasign/shale/releases/download/v0.1.26/shale_linux_arm64.tar.gz"
      sha256 "d84ceeecb6b90356d31c5d60f28138b1e21db06338756407db3f1ff1f3314444"
      define_method(:install) do
        bin.install "shale"
      end
    end
  end
end
