# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shale < Formula
  desc "Agent PR evidence — intent capture and session evidence rendered on pull requests"
  homepage "https://github.com/provasign/shale"
  version "0.1.18"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/provasign/shale/releases/download/v0.1.18/shale_darwin_amd64.tar.gz"
      sha256 "4f15a635f85541d8b6c10af4ce65f72e1a6d69963cb6845a213bab0a7007dc99"

      define_method(:install) do
        bin.install "shale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/provasign/shale/releases/download/v0.1.18/shale_darwin_arm64.tar.gz"
      sha256 "5b6595524c713cbf8e05d0081672e8702604cff6da2befeeda20bf4021fd0177"

      define_method(:install) do
        bin.install "shale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/provasign/shale/releases/download/v0.1.18/shale_linux_amd64.tar.gz"
      sha256 "a704bcadfa8c6fdf0ff7b9417f6b43ec0d981340ee5f9243dda3bb62f70cd32c"
      define_method(:install) do
        bin.install "shale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/provasign/shale/releases/download/v0.1.18/shale_linux_arm64.tar.gz"
      sha256 "4cccc75fb090bad065e035a7420adf7b141f784649d6101c3a6960a8341452af"
      define_method(:install) do
        bin.install "shale"
      end
    end
  end
end
