# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Shale < Formula
  desc "Agent PR evidence — intent capture and session evidence rendered on pull requests"
  homepage "https://github.com/provasign/shale"
  version "0.1.17"
  license "Apache-2.0"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/provasign/shale/releases/download/v0.1.17/shale_darwin_amd64.tar.gz"
      sha256 "9c1e8cf8c9aefacd61117785711054fce50abc70adce7b6fb9ca96dccac01977"

      define_method(:install) do
        bin.install "shale"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/provasign/shale/releases/download/v0.1.17/shale_darwin_arm64.tar.gz"
      sha256 "6a5cabb7ed4b530c8238f17b7aa448bdc0afc4b52b466e18b4ac9c4fd8cfc552"

      define_method(:install) do
        bin.install "shale"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/provasign/shale/releases/download/v0.1.17/shale_linux_amd64.tar.gz"
      sha256 "8ba0b74753e092dbadbe2564edb674b40a999fc0c878ddd8efa3df4ee01bb8a9"
      define_method(:install) do
        bin.install "shale"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/provasign/shale/releases/download/v0.1.17/shale_linux_arm64.tar.gz"
      sha256 "06bb8a92c63c36fb96e0ccb4552981a664c6190c5470d2b446167346e93475f6"
      define_method(:install) do
        bin.install "shale"
      end
    end
  end
end
